[package]
name = "hello-world-tcp"
version = "0.1.0"
edition = "2021"

[dependencies]
rama = "0.2.0-alpha.6"
shuttle-rama = "0.50.0"
shuttle-runtime = "0.50.0"
tokio = "1.28.2"
tracing = "0.1"
serde = "1.0"
serde_json = "1.0"
