[package]
name = "shuttle-axum-openai"
version = "0.1.0"
edition = "2021"

[dependencies]
async-openai = "0.23.0"
axum = "0.7.3"
serde_json = "1"
shuttle-axum = "0.49.0"
shuttle-openai = "0.49.0"
shuttle-runtime = "0.49.0"
tokio = "1.26.0"
